### PR TITLE
Resurrect newui-rendersurfaces

### PR DESCRIPTION
**Pull request by barrymoo**
This doesn't do beta orbitals yet, but I can work on that next.

### CODE REVIEW

**Comment by barrymoo** [comment]
One issue which existed before was: When the molecule is updated this interface breaks. I am working on trying to connect these processes, but I will be slow.

**Comment by cryos** [comment]
This looks good, I will be traveling later and would like to fix up a few minor issues I see in a follow up commit (removed copyright headers, some formats removed, and double check the functionality still works. Thanks for bringing this up to date @barrymoo! I think we can help with some of the other issues you mention, but it will be good to integrate this and iterate on further features/updates.

**Comment by barrymoo** [comment]
@cryos this is where https://github.com/OpenChemistry/avogadrolibs/issues/83 comes from. I can make a really nice interface with that functionality.

**Comment by cryos** [comment]
@barrymoo I know, I got that.

**Comment by cryos** [comment]
@barrymoo I was referring to copyright headers that had been removed above, and me adding them back in.

**Pull request merged**
