### PR TITLE
Add flatpak workflow for GitHub Actions

### PR DESCRIPTION
**Pull request by matterhorn103**
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ghutchis** [comment]
It's giving this error:
```
** (flatpak-builder:1007): ERROR **: 17:44:23.944: 
Failed to load included manifest (/__w/avogadrolibs/avogadrolibs/avogadroapp/flatpak/shared-modules/glew/glew.json): 
Failed to open file ?/__w/avogadrolibs/avogadrolibs/avogadroapp/flatpak/shared-modules/glew/glew.json?: No such file or directory
```

**Comment by matterhorn103** [comment]
Yep I saw. It's looking for the shared module relative to the path of the manifest and not to the root.

I could open a PR to keep the manifest in the top level of `openchemistry` (many projects do this), but then I would have to find a way to overwrite that manifest when building the release flatpaks.

I've added a step that manually moves the manifest up to the `openchemistry` top level, and I'm hoping that does the trick, as the source tree is then set up identically to the normal flatpak builds then I think?

**Comment by matterhorn103** [comment]
This is blocked by https://github.com/OpenChemistry/avogadroapp/pull/523 as it relies on the new manifest being in the correct location, so the build won't succeed just yet.

**Comment by ghutchis** [comment]
Let me know when this is ready for review, thanks.

**Comment by matterhorn103** [comment]
Now that the other PR has been merged, this should be ready now!

**Pull request merged**
