### PR TITLE
Get rid of bits/stdc++ headers - non-portable GCC header

### PR DESCRIPTION
**Pull request by ghutchis**
See https://stackoverflow.com/a/31816096/131896

Signed-off-by: Geoff Hutchison <geoff.hutchison@gmail.com>

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by cryos** [comment]
This fails for me locally when turning C++17 flag on, which is why I added it in the first place. Looking on the web the documentation is inconsistent but it definitely doesn't compile here with your branch and C++17 enabled:
```
In file included from /home/marcus/build/openchemistry/prefix/include/vtk-8.2/vtkRect.h:32,
                 from /home/marcus/build/openchemistry/prefix/include/vtk-8.2/vtkAxis.h:58,
                 from /home/marcus/src/openchemistry/avogadrolibs/avogadro/vtk/vtkplot.cpp:20:
/home/marcus/build/openchemistry/prefix/include/vtk-8.2/vtkMath.h: In static member function ‘static T vtkMath::ClampValue(const T&, const T&, const T&)’:
/home/marcus/build/openchemistry/prefix/include/vtk-8.2/vtkMath.h:1516:15: error: ‘clamp’ is not a member of ‘std’
 1516 |   return std::clamp(value, min, max);
      |               ^~~~~
ninja: build stopped: subcommand failed.
```
This is GCC 9.3.0, while Ubuntu is much older.

**Comment by cryos** [comment]
OK, I chose poorly - if we have a recent compiler that complies with C++17 properly then std::clamp comes from the STL `algorithm` header, I should have added that. C++ master also fixed that issue. Easiest would be to put algorithm in the deleted spots, harder would be update but likely worth doing.

**Comment by ghutchis** [comment]
I think it's building from VTK 9 right now from the `openchemistry` repo, which is why the automatic tests passed.

If you want to add <algorithm> that's fine with me.

**Review by cryos — APPROVED** [review]
Everything build and works if I move the VTK SHA forward - I am going to do that as I was a little sad about patching our code anyway...

**Comment by cryos** [comment]
It is odd that it built, but I just realized the CI is not building/enabling VTK so that makes sense.

**Comment by ghutchis** [comment]
@cryos - didn't realize that - i'll move the CI builds to enable more features for testing

**Pull request merged**
