### PR TITLE
WIP: Initial force field framework with gradients and some cleanup.

### PR DESCRIPTION
**Pull request by ghutchis**
Implements a Lennard-Jones calculator, including gradients
Optimization is handled by cppoptlib which offers
  template-based steepest descent, conjugate gradients,
  L-BFGS, and line-search methods
- [ ] Need to use separate thread and mutex for molecule
- [ ] Need simple "freeze atom" constraints
- [ ] Need to offer configuration to select methods
- [ ] Need to finish use of external programs (e.g., Open Babel)
 .. energy and gradients

Signed-off-by: Geoff Hutchison <geoff.hutchison@gmail.com>

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ghutchis** [comment]
This works, offering an "Optimize" and Calculate  ⇒ Energy method in the Extensions menu for the Lennard-Jones method.

The main reason for the WIP designation is that I'm looking for feedback before it's merged (i.e., anything glaring and bad from a design point).

**Comment by ghutchis** [comment]
A related change is at https://github.com/openbabel/openbabel/pull/1873
(i.e., the `obmm` tool would greatly help this, although I can write Pybel scripts to do similar things - not sure `pybel` is guaranteed to be installed, though)

**Comment by ghutchis** [comment]
I'm *not* going to clang-format the `cppoptlib` files - that would only complicate upgrading to future revisions.

**Comment by cryos** [comment]
I don't think you should change their formatting, but did you consider putting them in thirdparty? They are a third party library that appears pretty small, but may well have utility in other places in the future, it is also good to keep as much third party code in that prefix as possible, rather than bundling it with plugins, etc.

**Comment by ghutchis** [comment]
I'm closing this in favor of #448 -  I've moved the `cppoptlib` headers and will be finishing initial work on that in the next week.

**Pull request closed without merging**
