### PR TITLE
Move our OpenGL widget to the new Qt classes

### PR DESCRIPTION
**Pull request by cryos**

### CODE REVIEW

**Comment by cryos** [comment]
This fixes #128 when used with the accompanying commits in avogadroapp, but there are still one or two questions over there I need to figure out.

**Comment by ghutchis** [comment]
Is this ready for review?

**Comment by ghutchis** [comment]
I ask because of the comment about "more work to do"

**Comment by cryos** [comment]
Yes, I will try and get this finished up, there is some more clean up I need to do, but will hopefully get it finished up on the flights back today.

**Comment by cryos** [comment]
This is ready to go now, but must be used with the matching avogadroapp PR.

**Comment by cryos** [comment]
I will get this tested on Mac on Monday, I would like to get it merged soon. It works well on Linux.

**Comment by cryos** [comment]
Verified these work on retina displays, made some corrections. I am going to merge, and would appreciate feedback.

**Pull request merged**
