### PR TITLE
Update to latest Qt patch version and install-qt-action v4 in Qt6 Action

### PR DESCRIPTION
**Pull request by matterhorn103**
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by matterhorn103** [comment]
Qt 6.8.0 -> 6.8.1, which has [a lot of fixes](https://www.qt.io/blog/qt-6.8.1-released).

Also bumped the version of the `install-qt-action` to v4. Amongst other things there are relevant fixes for Qt 6.8 on Windows, and Windows on ARM support should we later want it.

There is an upgrade guide for `install-qt-action` [here](https://github.com/jurplel/install-qt-action/blob/master/README_upgrade_guide.md); I don't think any of it should be an issue.

The default settings in v4 and with Qt 6.8 align with the Windows-specific settings we had before so I dropped the separate step for Windows as it's now superfluous.

If everything looks good and merging is approved I'll update the `avogadroapp` action to match.

**Comment by matterhorn103** [comment]
@ghutchis I don't know anything about building on Mac – should we also be thinking about updating `MACOS_TARGET` and therefore indirectly `MACOSX_DEPLOYMENT_TARGET` from 10.15 to 12 (or higher I guess)? Qt 6.8 is [officially supported](https://doc.qt.io/qt-6/supported-platforms.html#macos) on macOS 12 or higher.

**Comment by ghutchis** [comment]
In priniciple `dependabot` should have found the `install-qt-action` update. No matter - the update is useful.

I agree with the update of `MACOSX_DEPLOYMENT_TARGET`. I doubt there are too many people still on 10.15, so 12 seems a reasonable target for the next release.

**Review by ghutchis — APPROVED** [review]

**Comment by ghutchis** [comment]
LGTM. I don't know what's going on with CodeQL, but that's not related.

**Pull request merged**
