### PR TITLE
Clean up the element colors to be more consistent with Jmol

### PR DESCRIPTION
**Pull request by ghutchis**
Roughly match Avo1 colors (from Open Babel) as well

Signed-off-by: Geoff Hutchison <geoff.hutchison@gmail.com>

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ghutchis** [comment]
I had a bit of time and went through up to Radon - anything past that looks like a minor +/-1 relative to Jmol anyway.

**Comment by ghutchis** [comment]
Avogadro 2 (with patch):
screen shot 2018-09-13 at 2 13 57 pm

Avogadro 1:
screen shot 2018-09-13 at 2 14 12 pm

**Comment by ghutchis** [comment]
I might want to shift the C color to be darker than Jmol and more consistent with Avo1.

Not sure about the build failure - it works here with no problems.
I’m also going to ignore clang-format which does bad things to the file.

**Comment by cryos** [comment]
This looks great, I would really like to get the BODR stuff updated as we use that to source data for VTK, vtk.js, and some of the Python stuff. Short term I think patching the header is fine, but having some project independent data is great. My FePt nanoparticle data looks much nicer now!
image

**Comment by ghutchis** [comment]
My guess is that the BODR is out of date at this point and would recommend that we create a new version (e.g., JSON or even CSV / tab-separated). I’m happy to post wherever, but I don’t want to deal with XML - I think Egon or someone else took my tab-separated tables for elements.xml.

Looking at the BODR elements.xml, it’s lacking recent symbols, element names, radii, etc.

**Comment by cryos** [comment]
Creating a JSON version of it would be great, and easier for us to use. As we want to use this data in a number of languages, something language agnostic would be very useful to avoid manually patching in a number of places. Agreed on being less inclined to deal with XML.

**Pull request merged**
