### PR TITLE
Initial MMTF support

### PR DESCRIPTION
**Pull request by frodofine**
I'm not sure what happened to the original PR, but here is a rebased version. It requires the changes in openchemistry project to be merged before the CI will pass.

Signed-off-by: Jonathan Fine <finej@purdue.edu>

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by cryos** [comment]
This looks good, it works but there only seems to be one frame and the unit cell doesn't look right. Screenshot below, if this is expected then things look good to me!
image

**Comment by ghutchis** [comment]
I don't think it's an animation formation - I'm pretty confident it should just be one frame.

I'd check the unit cell against the PDB rendering in Avogadro v1 for the same PDB code.

**Comment by cryos** [comment]
I was honestly asking @frodofine if both were expected, like I said if so I think this is ready to go.

**Comment by frodofine** [comment]
That's normal. The crystal cells in the PDB are notoriously bad (the atoms of the protein are rarely inside of the PBC). PyMOL and other renders have similar issues.

**Pull request merged**
