### PR TITLE
Io: Add an option to not perceive bonds in xyz

### PR DESCRIPTION
**Pull request by psavery**
Signed-off-by: Patrick Avery <psavery@buffalo.edu>

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by psavery** [comment]
@cryos This seems to work, although I am open to a better way to store and retrieve options in a std::string.

**Comment by psavery** [comment]
Done.

I also added a commit in this PR to add the io options arguments to the python bindings. I tried it out for xyz, and it seems to work. However, the default arguments in the python bindings do not seem to work for some reason. We have to pass in all arguments or we get an error similar to the following:

```
>>> ffm.readString(mol, xyz_data, "xyz")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: readString(): incompatible function arguments. The following argument types are supported:
    1. (self: avogadro2.FileFormatManager, arg0: avogadro2.Molecule, arg1: str, arg2: str, arg3: str) -> bool

Invoked with: <avogadro2.FileFormatManager object at 0x7f491a617f30>, <avogadro2.Molecule object at 0x7f491a56cba0>, '8\nEthane\nH      1.18508   -0.00384    0.98752\nC      0.75162   -0.02244   -0.02084\nH      1.16693    0.83301   -0.56931\nH      1.11552   -0.93289   -0.51453\nC     -0.75159    0.02250    0.02089\nH     -1.16688   -0.83337    0.56870\nH     -1.11569    0.93261    0.51508\nH     -1.18499    0.00442   -0.98752', 'xyz'
```

**Comment by psavery** [comment]
I have figured out how to get the pybind11 default arguments to work. But I'll submit it in a separate PR after this one is merged (unless I should add it to this one as well)...

**Comment by cryos** [comment]
For the Python bindings there is a way to have default arguments, it is escaping me right now. We can probably cope with small change for now, but it would be good to support defaulting to empty.

**Comment by psavery** [comment]
I added my commit with the pybind11 default arguments. Unfortunately, if you add one py::arg, you have to add them all.

I tested this myself and it seems to work as it should.

**Pull request merged**
