### PR TITLE
Bump to Ubuntu 22.04 LTS for AppImage builds

### PR DESCRIPTION
**Pull request by matterhorn103**
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by matterhorn103** [comment]
This is in line with the policy outlined [here](https://discuss.avogadro.cc/t/appimage-ssl-issues/5260/6) of building for the Ubuntu LTS release *prior* to the current one. Now that 24.04 is available, we should move to 22.04.

Of key significance is that this should fix the SSL issues on Linux (closes #1464), as 22.04 has OpenSSL 3.0 and therefore the Qt it provides will also be built against OpenSSL 3.0. Anyone who was running the AppImage on 22.04 or other modern distros won't have been able to use the plugin manager, but will now have that restored.

**Comment by ghutchis** [comment]
As long as the AppImage builder doesn't complain, I'm good. (At one point, the AppImage tool was very picky about what OS it ran on.)

**Comment by ghutchis** [comment]
But you also have this change in your other pull request. I can't merge both, so I'm going to close this one.

**Comment by matterhorn103** [comment]
> But you also have this change in your other pull request. I can't merge both, so I'm going to close this one.

Maybe I misunderstood how git works then, I thought it'd be fine since it's the same commit in each branch. Fair enough!

**Pull request closed without merging**
