### PR TITLE
chore: fix typos and spelling inconsistency

### PR DESCRIPTION
**Pull request by e-kwsm**
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Review by ghutchis — APPROVED** [review]

**Comment by ghutchis** [comment]
Looks good - can you please take care of the sign-off:
https://github.com/OpenChemistry/avogadrolibs/pull/1174/checks?check_run_id=8591464496

**Comment by ghutchis** [comment]
I'm really surprised the `misspell-fixer` action isn't finding these. Are you using a tool we can add to the automated actions?

**Comment by e-kwsm** [comment]
> Looks good - can you please take care of the sign-off:

I signed off the commit.

> I'm really surprised the `misspell-fixer` action isn't finding these. Are you using a tool we can add to the automated actions?

I use https://github.com/crate-ci/typos, but it gives many false positives, e.g. "Nd" (neodymium) is considered as a misspelling of "And".

**Comment by ghutchis** [comment]
Maybe we can set up a filter list... I'd be happy to add a [`_typos.toml`](https://github.com/crate-ci/typos/blob/master/docs/reference.md) .. the current action doesn't seem to help much.

Would you be willing to set up the false-positive filter?

**Comment by e-kwsm** [comment]
There are so many false positives that it is, I believe, burdensome to list them up. Also, I did not change function names for compatibility, e.g.,
https://github.com/OpenChemistry/avogadrolibs/blob/1dfa8ae490be1b792ae535d4da72e1def96cf86e/avogadro/core/graph.h#L197
must be `checkConnectivity`.

**Pull request merged**
