### PR TITLE
Update element info in tests

### PR DESCRIPTION
**Pull request by psavery**
A few elements were renamed in PR #80, and some element
info (masses, radii) was updated in PR #117. This commit
updates those changes in the tests so that they pass.

### CODE REVIEW

**Comment by psavery** [comment]
This update makes it so all the tests in PR #201 pass.

**Comment by psavery** [comment]
I see that the clang-format failed. Do you think that is worth changing? I'll do it if you do.

**Comment by ghutchis** [comment]
No, this looks fine.

**Comment by psavery** [comment]
Thanks Geoff! Looks like the tests in #201 pass now!

**Pull request merged**
