### PR TITLE
Search for the generators in a sibling repository

### PR DESCRIPTION
**Pull request by cryos**
Remove the generators from the repository, and search for them in a
sibling repository, this will be added to the superbuild so that it
is present when packaging.

Signed-off-by: Marcus D. Hanwell <marcus.hanwell@kitware.com>

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by cryos** [comment]
This fixes #149 when coupled with the superbuild update.

**Comment by ghutchis** [comment]
This is okay, but I'd much rather match everything with *.py and then use LIST(REMOVE_ITEM ..) to remove the test script. 

Consider that I just added the orca.py script and I'm sure we'll gain more over time.

**Comment by ghutchis** [comment]
I'm also troubled by the use of the "unique hidden file" - why is this needed?

**Comment by cryos** [comment]
It doesn't seem that troubling to me, it is a really simple double check that the repository is what we think it is. You could also have a directory with that name that happens to be something else, and I wanted to be reasonably certain as the repository isn't necessarily in a clean superbuild.

I added the orca file, I think the risk is minimal, I want to ensure the build is consistent. Globs can get out of date, but I could take a look at adding a CMake file listing all plugins in the repository. I was hoping to keep it simple, but agree it would  be preferable to keep a listing of files to be installed in the repository. I can likely make that the uniquely named file too, and have it serve the dual purpose.

This is just aimed at packaging releases, and the generator SHA needs pushing forward before releases.

**Comment by ghutchis** [comment]
You can use the plugin.json file:
```
grep url plugin.json  | cut -d '"' -f 4 # gives https://github.com/openchemistry/avogenerators
```

If you want the list of commands:
```
grep 'command' plugin.json | cut -d '"' -f 4
```

**Comment by ghutchis** [comment]
The point of the plugin.json was to give a short manifest useful for the plugin loader (#303) the download feature, and eventually a plugin directory. We picked JSON because basically everything else was based on JSON.

It offers a list of commands, since plugin authors might want to have other files in the directory that aren't commands. (Personally, I'd suggest copying the whole `avogenerators` directory on install, since i18n efforts will introduce translation files.)

**Comment by cryos** [comment]
The grep and cut commands are not available in all build environments, and so that would be a terrible idea. JSON is great, but CMake doesn't currently ingest it, I don't want to move to something where we are just globbing blindly as that is unreliable and would be a setback. You asked for recommendations, this is my recommendation, I see your point about some duplication, but think that it is worth it to have a reliable build environment while still supporting some separation.

**Comment by cryos** [comment]
I see the desire for *one true way*, but don't think adding a single file that contains a listing is files to install is unreasonable. We have two distinct goals, to install and distribute the generators with the binary bundles, using specific SHAs specified in the superbuild, and to dynamically download updates between releases/outside of releases that can override these files should users wish.

Using hackish solutions to avoid adding a file that can specify to the CMake build system unambiguously what should be installed is unreasonable IMHO. Maybe we should just copy the avogenerator code periodically back into this source tree right before releases, and leave things as they are. That would make it obvious when new files are added, and give an opportunity to update the build system here instead.

I can close this PR and plan on that if preferred.

**Comment by ghutchis** [comment]
The .cmake file is not a big deal. Obviously, I'd rather ingest the JSON, but it's fine. I was writing my comment about the same time you were making that change - so the wires crossed. The main point should be that `avogadrolibs` shouldn't keep a fixed list of scripts - it should get the list from `avogenerators`

I stand by my point that creating a unique hidden file as a way to identify a repository isn't a good solution. Are there really going to be many directories labeled as 'avogenerators' that happen to be in that particular path? Seems unlikely IMHO.

**Comment by cryos** [comment]
The hidden file is a simple way to be much more certain that it isn't an empty directory where the --recursive/git submodule update --init hasn't been used, or a bad tree checked out, or other possibilities that can be more subtle to debug and mitigated by a simple check.

I think it is much cleaner keeping the listing in the other repo, and that conveniently gives a uniquely named file that has the information requested,  with a clean path to bail if not present. I prefer to err on easy to debug/increased certainty after working on complex builds for many years, and the cost is pretty minimal. I want to keep things as robust as reasonable.

**Comment by ghutchis** [comment]
The appveyor build has been really flaky. I'm okay to merge if you're okay with ignoring that build failure.

(Not sure if there's another way to get Windows build tests.)

**Comment by cryos** [comment]
It is obviously not related to this branch, merging, then I will prepare an updated superbuild commit that uses the new avogadrolibs and avogadrogenerators SHAs. Thanks for talking this through, I think this is a reasonable compromise that will be pretty robust.

**Pull request merged**
