### PR TITLE
Dalton plugin

### PR DESCRIPTION
**Pull request by cryos**

### CODE REVIEW

**Comment by ghutchis** [comment]
Why did you push this? I didn't have time to do it, but I'd much rather solve this on the Python side (e.g. a method that applies Dalton style to the atoms after sorting).

**Comment by ghutchis** [comment]
Oh, I see, this supersedes the other branch. Still, I'd rather handle in Python.

**Comment by cryos** [comment]
I think there is a decent argument for doing this on the C++ side, although not in the way chosen. It can be handled on the Python side, but I wasn't aware of any other work, and want to move it forward. Even if we refactor, I wanted to understand their needs better and test it out.

**Comment by ghutchis** [comment]
I'm closing this - it's solved by #200

**Pull request closed without merging**
