### PR TITLE
Format absolutely everything with clang-format

### PR DESCRIPTION
**Pull request by matterhorn103**
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by matterhorn103** [comment]
This way the clang-format check won't just fail for every single PR :)

Merging this would significantly inflate the number of lines of code I have supposedly "contributed", in a fairly artificial way, so I'd understand if you didn't want to merge on that basis. Feel free to just use the diff to make a new PR where you're the author, @ghutchis

**Comment by ghutchis** [comment]
Something really failed here -- the `#include` are in the wrong order. I'm going to close this. I'll see what I can do to fix the `clang-format` complaints, but it's not high on my priority list. (Correct, good code is what matters.)

**Comment by matterhorn103** [comment]
That's fine by me. My logic previously was that if every file that gets changed gets formatted, the codebase will gradually get cleaned up anyway. I just got fed up of being told that I hadn't formatted my PR correctly haha. Is there a way to restrict the automatic formatting check to those files which a PR has touched?

**Comment by ghutchis** [comment]
The action already uses diff. I don’t know why it’s failing, but I’ll
investigate - it’s just not high on my list during a busy week.

**Pull request closed without merging**
