### PR TITLE
Fixes for Qt6 compilation resubmission

### PR DESCRIPTION
**Pull request by matterhorn103**
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by matterhorn103** [comment]
Sorry, I am still getting to know Git/GitHub and didn't realise that moving my commits to a different branch and making my master the same as upstream master would close the old PR #1455. Reopened this from my new branch.

**Comment by ghutchis** [comment]
Thanks - beyond the minor merge conflict, you will need to sign off your commits with your name:
https://github.com/OpenChemistry/avogadrolibs/pull/1466/checks?check_run_id=19016856565

**Comment by matterhorn103** [comment]
Yes I realized that after opening one of the two PRs (this or the avogadroapp one) and have been using that for more recent commits I believe. Is it ok for now (since my name is in there anyway with the same email on other commits) or should I look at changing the git commit history?

**Comment by ghutchis** [comment]
Since I'm probably going to squash on merge, that's probably okay, thanks.

**Comment by matterhorn103** [comment]
@ghutchis By the way, I have a suspicion that several of the fixes I made were to code that you added since @cryos' work was merged back in April, because presumably everything compiled ok for him back then.

Can I suggest that the new checks for Qt6 builds in #1282 (at least the Ubuntu and AppImage ones) get added sooner rather than later to try and avoid too much divergence?

That might help to reduce the remaining workload once you do decide to switch to Qt6 next year. Would also allow testing of Qt6 AppImages as we go along :)

**Comment by ghutchis** [comment]
Sure, let's see if we can get some Qt6 builds going again.

**Pull request closed without merging**
