### PR TITLE
Tweak icons for label editor and selection

### PR DESCRIPTION
**Pull request by ghutchis**
Signed-off-by: Geoff Hutchison <geoff.hutchison@gmail.com>

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ghutchis** [comment]
Here's a preview - I think this clarifies that it's to write out atom labels:
Screen Shot 2021-09-08 at 5 52 52 PM

**Comment by ghutchis** [comment]
For the selection tool, the molecule didn't show well at 32x32.

I tried a big "I" or text-editing label and it didn't show very well at scaling either. Using "A" or "T" might be better. I also considered a letter that's bigger than the atom. 😄 

I'm thinking of posting some open requests for graphic designers. (We have a bit of $$ from Google as a mentoring org.)

**Comment by cryos** [comment]
It seems a little convoluted as an icon, not a big fan, but I have seen far worse 😄

**Comment by ghutchis** [comment]
Yeah, that's why I'd like to get an icon designer to do them 😄  I posted with Open Source Design, so hopefully we'll get some interest.

**Comment by ghutchis** [comment]
I'll merge these for now...

**Pull request merged**
