### PR TITLE
Dev extensions

### PR DESCRIPTION
**Pull request by research11111**
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by research11111** [comment]
This pull request addresses Issue #1391 and includes the following enhancements:

- Sets the Python path similarly to how the `quantumInput` extension does.
- Partial support for `virtualenv`; manual path input is required from the user.
- Enables the addition of custom plugin URLs (GitHub-hosted only).
- Allows local download of the `plugins.json` file and the ability to add entries to it.
- Supports installations both with and without Conda.
- Features auto-detection of existing installations.
- Automates the installation of dependencies, either from `requirements.txt` or `pyproject.toml` (https://github.com/research11111/avogadro-rdkit/ may be used to validate).

**Comment by ghutchis** [comment]
I appreciate the work. We would like significant contributions to `avogadrolibs` to use the git signify with your full name, e.g.
git config --global user.name "FIRST_NAME LAST_NAME"
git config --global user.email "MY_NAME@example.com"
https://github.com/OpenChemistry/avogadrolibs/pull/1417/checks?check_run_id=18132420984

**Comment by ghutchis** [comment]
I'll look through and review, but at some point the changes to `i18n` need to be removed, since it's unrelated and we don't want to alter translations. (I can do that if you're not sure.)

**Comment by research11111** [comment]
- yes please, no matter for translation changes (I was not sure about filename in comments)
     
 - I reserve myself write to keep anonymous for my research preventing any interference with my daily life and ask you to respect that
 
 Yes trust based on new people coming on internet from all world is hard thanks

**Comment by ghutchis** [comment]
> * I reserve myself write to keep anonymous for my research preventing any interference with my daily life and ask you to respect that

That is, of course your choice, but in that case, I'm afraid we cannot accept your code into Avogadro.

You are of course, welcome to submit issues, feedback, discuss, add script plugins, or anything else. But one of the requirements for pull requests to avogadrolibs is a sign-off with a real name.

**Comment by ghutchis** [comment]
I *think* I have now re-implemented this work in #1559 and #1562 - I greatly appreciate bringing up the issue and the pull request.

I'm going to close this, but if you have concerns / issues with the new features, please open a new issue - I want to get it right. Thanks!

**Pull request closed without merging**
