### PR TITLE
Create config.yml

### PR DESCRIPTION
**Pull request by ghutchis**
Add a config for the welcome bot:
https://github.com/behaviorbot/welcome

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by cryos** [comment]
Can you add the signed-off line? I think this looks good, I wonder if we might just link to the DCO in the pull request template so that we don't create tons of boilerplate - the bot is good at linking to the full text if it isn't there.

**Comment by ghutchis** [comment]
The DCO doesn't seem to like me. I don't know how to add the sign-off on the 1st commit, but it's complaining about my second commit, which does have the sign-off.

Any ideas? Can we add a dco.yml to ignore org members?

**Comment by cryos** [comment]
Ah, yes, each commit needs it, `git commit --amend` is your friend, along with `git commit add file`, or in this case `git rebase -i HEAD~2` and you could just combine the two together/add the -s flag to add in the sign off. I am thinking about just adding some of these tips to the pull request template to streamline it, thank you for being a guinea pig.

**Comment by ghutchis** [comment]
This is crazy. Is the problem the initial? It flags all my commits, despite the signed-off line.

**Comment by cryos** [comment]
I just gave it a quick try, and the [commit hook](https://stackoverflow.com/questions/15015894/git-add-signed-off-by-line-using-format-signoff-not-working/46536244#46536244) can automatically invoke -s, and worked in my brief testing. I hate creating different rules for different people, I use -s and -v a lot when I commit.

You have to actually edit the commit, and force push it. I can just merge anyway, but adding more commits will not fix the initial commit not being signed off. That is how it is intended to work.

**Comment by ghutchis** [comment]
I rebased and force-pushed, and you can see that both the commit and the merge commit have signed-off lines.

**Pull request closed without merging**
