### PR TITLE
An initial set of selection commands.

### PR DESCRIPTION
**Pull request by ghutchis**

### CODE REVIEW

**Comment by cryos** [comment]
This works well locally, but I end up with a select menu at the top level that looks like this:

image

This is with avogadroapp at master, things get worse as I said in the review of the menu builder branch when switching to that branch (or stay the same in the case of this menu).

**Comment by cryos** [comment]
I hadn't appreciated you want a separate selection menu, so this seems fine although I think the QAction with a - looks odd - does this look different in Macs? The functionality worked as expected for me.

**Comment by ghutchis** [comment]
It shows up as a separator. I'll try to sort out the UI issues.

I wanted a selection menu, because I think there are a bunch of useful tools for selections:
* Enlarge selection by X Angstroms
* Select all Fe atoms
* Select all Tyr residues
* Select all water molecules
* Save selection (e.g., for QM fragment calculations)

Chris Wilmer here was pointing out that CAD programs have a lot of useful tools for operations on selections - adding, subtracting, intersections, etc.

**Comment by cryos** [comment]
Thought I had commented on this, it sounds great and he makes a good point.

**Comment by ghutchis** [comment]
I'm not 100% sure this commit fixes the problem or if I need to handle some with the menubuilder branch in avogadroapp.

**Comment by ghutchis** [comment]
Part of the problem in the screenshot you give, is that menu builder will sort menu items alphabetically, which is a disaster. Plugins should be able to supply actions in an ordered list, which is the point of that branch.

**Comment by cryos** [comment]
That is fair enough, but the duplicates it creates at present on Linux are pretty disastrous too. I can try debugging that further, but I think the root cause is that Qt doesn't guarantee that OS plugins won't change the user visible text and that it can't be used as a unique identifier. I will give this branch a try now.

**Pull request merged**
