### PR TITLE
3DMol Simple Plugin

### PR DESCRIPTION
**Pull request by barrymoo**
This is the scaffold for the 3DMol Plugin. Initial code will just write the XYZ coordinates (when complete). May need to work with 3DMol to get further functionality we would like (for example camera position).

To Do:
- Ctrl-C uses the copypaste plugins (i.e. copies cjson to clipboard, need to override this), use right-click-copy for now
- Add more functionality:
  - Visualization type (stick, ball and stick, etc.)
  - Cubes
  - Deal with PDB files

### CODE REVIEW

**Comment by cryos** [comment]
Cool, all of the files are currently missing a copyright header. Didn't have a chance to test, but this would be an awesome addition. The work I did with 3DMol last year deals with exporting Avogadro2 data (molecules + cubes) to 3DMol, it had custom JavaScript to load in the cubes, and then add controls. https://openchemistry.kitware.com has some examples, I wonder if that might help, and whether any could be integrated, or the formats I was generating could be pushed into something they already have.

**Comment by barrymoo** [comment]
When I was working on the surfaces interface you asked me to remove them? I can add them back in if you would like.

3DMol is developed on campus here and I am meeting with them in a few weeks. It should be easy to share code and thoughts back and forth. For example, it would be nice if I could input a camera position to keep everything consistent between the two.

**Comment by cryos** [comment]
> When I was working on the surfaces interface you asked me to remove them? I can add them back in if you would like.

I don't know what you are referring to in that statement, sorry I made need more coffee.

**Comment by barrymoo** [comment]
I think I took this comment to mean the opposite thing regarding copyright headers: https://github.com/OpenChemistry/avogadrolibs/pull/62#issuecomment-227740500. I will simply add them back in. I can do the same for the surfaces interface.

**Comment by cryos** [comment]
All files should have the standard copyright header stating license etc. I was reading that more and more lists of copyright holders/years are considered unnecessary, and are maintained far more accurately by git. I don't remember suggesting you remove the copyright headers, please accept my apologies if I did so in error.

**Comment by ghutchis** [comment]
Bump. Can we merge this one?

**Comment by cryos** [comment]
Sure, works for me here.

**Pull request merged**
