### PR TITLE
Basic test for LAMMPS dump

### PR DESCRIPTION
**Pull request by badarsh2**
This PR adds a basic test for LAMMPS reader.

### CODE REVIEW

**Comment by badarsh2** [comment]
I noticed that the avogadrodata module is out of sync in the superbuild. I guess that has to be updated for the tests to pass.

**Comment by badarsh2** [comment]
I've completed the tests by including more cases from the trajectory, and have integrated the timestep field with the reader too. 
A gentle reminder to update the `avogadrodata` repo in the superbuild.

**Comment by cryos** [comment]
The superbuild has been updated.

**Comment by badarsh2** [comment]
:+1: 
If this PR is good to go, it can be merged.

**Pull request merged**
