### PR TITLE
Updated spacegroupdata.h to match current Open Babel data

### PR DESCRIPTION
**Pull request by psavery**

### CODE REVIEW

**Comment by psavery** [comment]
This is submitted in response to comments in #153. I wrote a script to find all Hall symbols that we use here in the Open Babel space-groups.txt file and copy over their transformations to the appropriate locations.

Thanks to ClangFormat, it is easy to view the changes.

I've noticed that some of the lines are just small re-orderings. Although there are also several sign changes here and there.

Please let me know if there appear to be any problems with this.

**Comment by psavery** [comment]
Nevermind, I just found a bug. Give me a second to correct it.

**Comment by psavery** [comment]
Okay. As far as I can tell, I think my script worked this time around. Let me know what you think.

**Comment by ghutchis** [comment]
Maybe we can commit the script as well?

**Comment by ghutchis** [comment]
Otherwise, this looks fine.

**Comment by psavery** [comment]
Sorry for the delay. I was traveling around the holidays.

Yes, I will make the script a little more user-friendly and add it in soon.

**Comment by psavery** [comment]
Okay. I added the script. Let me know if there are any other changes needed.

**Comment by ghutchis** [comment]
Looks okay to me.

**Pull request merged**
