### PR TITLE
Add "…" indicator for display types with settings

### LINKED ISSUE #1529: View Configuration pane is empty
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.98.1
 - Qt: 5.15.11
 
The bug applies to both an up-to-date self-compiled version and the nightly AppImage. As I wasn't aware that the pane should have anything in it, I guess this bug has always existed.

**Desktop version: (please complete the following information):**
 - OS: openSUSE Tumbleweed
 - Version: snapshot 20231213
 - KDE Plasma Version: 5.27.10
 - KDE Frameworks Version: 5.112.0
 - Kernel Version: 6.6.6-1-default (64-bit)
 - Compiler (if you built from source)

**Describe the bug**
The view configuration pane is completely empty for all tools.

**Expected behavior**
Screenshots of the macOS version at two.avogadro.cc indicate that the pane should be populated.

**Screenshots**
Screenshot_20231215_014900

### PR DESCRIPTION
**Pull request by ghutchis**
Fix #1529

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ghutchis** [comment]
Full change requires a patch to avogadroapp too.

**Comment by ghutchis** [comment]
Final version looks like this:
Screenshot 2023-12-18 at 7 29 27 PM

Thoughts @matterhorn103

**Comment by matterhorn103** [comment]
> Final version looks like this: Screenshot 2023-12-18 at 7 29 27 PM
> 
> Thoughts @matterhorn103

@ghutchis Personally I think that looks great and works well! Makes the extra settings much more discoverable. You?

The only thing I will say is that normally three Unicode bullets ••• get used in UI design, so they're fatter and on the median not the baseline, not an ellipsis …

Is using the Unicode possible? Presumably, since a true ellipsis character is used in the menus.

**Comment by matterhorn103** [comment]
Examples from Github, Spotify, OneNote, WhatsApp, and the iPhone notes app.

All middle-aligned, not on the baseline.

IMG_1121
IMG_1122
IMG_1123
IMG_1124
IMG_1125

**Pull request merged**
