### PR TITLE
Fix in file export path

### PR DESCRIPTION
**Pull request by badarsh2**
In issue https://github.com/OpenChemistry/avogadrolibs/issues/282, I had mentioned about a problem with png export in Windows. Turns out that it did get exported, but in the wrong path. This patch assigns the proper path to the destination file.

### CODE REVIEW

**Comment by ghutchis** [comment]
If you make the minor changes and fix the conflicts, I'm happy to merge.

**Comment by badarsh2** [comment]
I've made the changes.

**Comment by cryos** [comment]
Looks fine to me, once @ghutchis approves I think we can merge this.

**Comment by ghutchis** [comment]
Sorry, I forgot this one.

**Pull request merged**
