### PR TITLE
Update Qt5 patch version

### PR DESCRIPTION
**Pull request by matterhorn103**
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by matterhorn103** [comment]
Just opened this PR so I can test the build artifacts that GitHub Actions produces.

**Comment by ghutchis** [comment]
I'm happy to bump the Qt version if it's available. (I didn't bother because they were supposedly only for commercial users.)

**Comment by ghutchis** [comment]
You can get the current list of available versions here: https://ddalcino.github.io/aqt-list-server/

The most recent open source qt5 binary release is 5.15.2

(Some Linux have newer versions because they build from source.)

**Comment by matterhorn103** [comment]
It seemed to fail when I tried 5.15.15. Trying 5.15.8 now. How can I know/find out which versions are available?

**Comment by ghutchis** [comment]
Not through the official qt5 releases: 5.15.2 was the last binary release unless you're a commercial license.

As I mentioned on your bug report, does the qt6 version run plugins? If so, does it exhibit the bug?

Probably better to just work towards finishing the migration to qt6.

**Comment by ghutchis** [comment]
IIRC the new Qt 6.8 has full support for Windows ARM and Linux ARM, which would be a nice target.

**Pull request closed without merging**
