### PR TITLE
Check for current palette being a dark theme

### PR DESCRIPTION
**Pull request by matterhorn103**
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by matterhorn103** [comment]
@ghutchis as far as I can tell, the code you just merged doesn't actually switch to dark mode because `darkTheme` doesn't get set anyway (other than to `false` by default).

This is code to set that based on a solution that Qt suggest for pre v6.5, which seems to be successful as if I print the value of `darkTheme` on my system it comes out as `true`.

Unfortunately I can't seem to make the inheritance work such that it triggers the `if` statement in each individual tool.

**Comment by ghutchis** [comment]
See https://github.com/OpenChemistry/avogadroapp/pull/458

**Comment by ghutchis** [comment]
I think it's much better to have the dark / light code in `avogadroapp` because it can get the theme change signal (in Qt 6.5) and tell all the tools to change their icons.

**Comment by matterhorn103** [comment]
Oh dear, that's very embarrassing. I hadn't even seen that other commit, as I don't pay as much attention to the `avogadroapp` repo. Sorry!

Could have saved myself a couple of hours of trying to work with c++  :'(

**Comment by ghutchis** [comment]
No worries. The `avogadroapp` repo doesn't do as much work as this one.

**Pull request closed without merging**
