### PR TITLE
Create Libmsym Extension

### PR DESCRIPTION
**Pull request by ghutchis**
Initial work from Marcus J. for a symmetry extension in Avo2

### CODE REVIEW

**Comment by cryos** [comment]
Awesome, I will see if I can resolve the conflicts, and take a look at this.

**Comment by ghutchis** [comment]
This is work in progress, but makes a lot of headway for visualizing symmetry elements and exploring symmetry.

I can also imagine rendering performance improvements for symmetric systems.

**Comment by cryos** [comment]
What rendering performance improvements, how big do symmetric systems this treat get? Even on modest graphics cards rendering a million atoms is interactive so I wonder if that would be a good focus, detection and rendering of symmetry is extremely important.

**Comment by ghutchis** [comment]
I'm thinking less of rendering atoms and more about orbitals and surfaces, etc. But I've thrown nanotubes at libmsym and gotten fraction-of-a-second response.

**Comment by ghutchis** [comment]
(i.e., if you know that you have C60 or C540 and it's I<sub>h</sub>, you can save on computing some of the orbital calculations... similarly with large nanotubes that might have symmetry.)

**Comment by ghutchis** [comment]
I'm going to drop this pull request. Marcus J has a libmsym supposedly without requiring VLA, but this branch needs substantial updates. I'll create a new request once I've updated this.

**Pull request closed without merging**
