### PR TITLE
Save and read atom selections to CJSON.

### PR DESCRIPTION
**Pull request by ghutchis**
As part of the "atoms" dictionary, e.g.

    "selected" : [ 1, 1, 0, 0, 0, 0, 0, 0 ]

This will allow input generators and other scripts to get the selected atoms if they want/need them.

### CODE REVIEW

**Comment by ghutchis** [comment]
I think a more substantial CJSON spec will be needed soon. I will make an initial after Christmas.

**Comment by cryos** [comment]
What form do you want a spec in? I am working on a paper with Bert documenting our work on JSON for chemical representations, and it would be great to know what you mean so that might be more useful. We are certainly working on fleshing out the details, and I have talked with Stuart about chemical JSON and we set up the repository as a project neutral place to flesh out such a spec.

**Comment by ghutchis** [comment]
I think most people would be fine with a set of Markdown (or similar) expressing:

- All required attributes
- Optional attributes

I'm thinking of something similar to http://opensmiles.org/opensmiles.html

For example, in the Python workflow code, we realized some molecules only have fractional coordinates. Similarly, we discussed the optional 3DTuple attribute..

* Another example - if something returns atoms, but no bonds section, is that OK? 
* Should all bond orders be specified?
* How do you specify an overall charge on a molecule (e.g., benzene anion)?

This came up during GSoC and again with Paul and the workflow code. Having more concrete documentation about what's required, what's common, what's optional is very useful.

**Comment by cryos** [comment]
This is great feedback, and something I can work on in the chemicaljson repo, and we could edit/patch up there. Thanks Geoff, I will see if I can get something basic together soon. We want to have this paper finished up by the end of the calendar year, and this would be a good document to author.

**Comment by ghutchis** [comment]
Seems like you're already writing the same bits for the manuscript. Thanks.

**Pull request merged**
