### PR TITLE
Added DALTON input generator.

### PR DESCRIPTION
**Pull request by sowikse**

### CODE REVIEW

**Comment by cryos** [comment]
Thanks, I will take a look at this soon. It looks like there re a few small formatting issues, and I would  like to wrap my head around the additions proposed to coordinate generation code.

**Comment by cryos** [comment]
Sorry about the delay, I will go through, and do a little testing, I want to merge this before we tag a new release.

**Comment by ghutchis** [comment]
I'm wondering a bit on strategy - should we change the script API a bit to allow (or require) scripts to format the coordinate blocks themselves?

**Comment by cryos** [comment]
The scripts should be able to format themselves, I haven't dug into this one yet, but the design was to allow either way to be true. You have to insert a special block to be replaced.

**Comment by ghutchis** [comment]
@sowikse - can you give me an example or two of the input coordinate format you want? I think I can write the Python version and get this merged.

**Comment by ghutchis** [comment]
It's something like this, right?

<pre>
Charge=6.0 Atoms=6
C             3.4072170000    0.4963900000   -0.0515280000 
C             2.1785960000   -0.3844230000   -0.0266180000 
C             0.9021970000    0.4415910000   -0.0168210000 
C            -0.3314170000   -0.4460760000    0.0079410000 
C            -1.6051920000    0.3859780000    0.0192890000 
C            -2.8325630000   -0.5042740000    0.0430960000 
Charge=16.0 Atoms=1
S            -4.3230180000    0.5494580000    0.0608310000 
Charge=1.0 Atoms=14
H             3.4278940000    1.1375720000   -0.9428560000 
H             3.4506170000    1.1562530000    0.8252500000 
H             2.2057290000   -1.0469110000    0.8614340000 
H             2.1816520000   -1.0628780000   -0.9029270000 
H             0.8746690000    1.1041760000   -0.9053890000 
H             0.8985940000    1.1205200000    0.8597710000 
H            -0.3026670000   -1.1095600000    0.8958630000 
H            -0.3277720000   -1.1235860000   -0.8697630000 
H            -1.6329670000    1.0488370000   -0.8696430000 
H            -1.6084200000    1.0626250000    0.8982380000 
H            -2.8124720000   -1.1648960000    0.9289740000 
H            -2.8398430000   -1.1739920000   -0.8360870000 
H            -5.2374200000   -0.3839880000    0.0779960000 
H             4.3265830000   -0.1028160000   -0.0570500000 
</pre>

**Comment by cryos** [comment]
#186 supersedes this branch, I am going to test it locally. I would like to see if all of the C++ code is necessary, but I think it would be good to get the Dalton input generator in soon even if we refactor it in the future.

**Pull request closed without merging**
