### PR TITLE
Use the new --noh flag in Open Babel 3.0.1 and later

### LINKED ISSUE #442: Open Babel Optimize Geometry arbitrarily adds H atoms
**Avogadro version: 1.93.0:**
 - Avogadrolibs: 1.93.0
 - Qt: 5.12.5

**Desktop version: :**
 - OS: Linux  (Debian unstable)
 - Version linux 5.4.13-1
 - Compiler g++ 9.2.1 20200203

**Describe the bug**
The Optimize Geometry function sometimes fails, with the optimizing routine apparently arbitrarily adding its own H atoms contradicting the given structure.  Optimize Geometry appears to run for a reasonable number of iterations, but then gives the error message:
"Number of atoms in obabel output (22) does not match the number of atoms in the original molecule (19)."
(This example of 19 atoms refers to histidine with the carboxylate group protonated  and prime amine group unprotonated i.e. ...NH with 1 H atom, no charge. That is, neutral histidine)

The problem seems to happen for pH-dependent molecules such as amino acids, where carboxylate and amine groups may or may not be protonated.

If I manually click on "Adjust Hydrogens", then avogadro2 adds 3 protons, 1 to the  amine group and 1 each to the C and double-bonded O of the carboxylate.  So it's converting the carboxylic acid group to a methandiol group.  By the count of atoms in the error message, it looks like this is what Optimize Geometry is doing to the structure before running optimization.

So it looks as though Optimize Geometry is interfering with the given structure and not working with the structure as presented.

**To Reproduce**
1. Create an amino acid. Glycine will do.  If "Adjust Hydrogens" is set. then avogadro2 will create the amine group as ...NH2 (glycine cation).
2. Delete one of the amine hydrogens to get neutral glycine H2CNHCOOH
3. Click Extensions->Open Babel->Optimize Geometry.
4. Iterations will proceed, then give the error message
"Number of atoms in obabel output (10) does not match the number of atoms in the original molecule (9)."

**Expected behavior**

Optimize Geometry should work strictly with the given structure, and not add (or remove) hydrogen atoms.

### PR DESCRIPTION
**Pull request by ghutchis**
Ensures hydrogens are not added automatically.
Fixes #442 (and probably other issues)

Signed-off-by: Geoff Hutchison <geoff.hutchison@gmail.com>

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ghutchis** [comment]
This will require a bump for openbabel-3-0-1 or at least https://github.com/openbabel/openbabel/commit/4b228ac2833429b0c336eab3acffd8cffe7c605b

OTOH, it will greatly help with several complaints (e.g. Open Babel automatically adding hydrogen atoms).

**Comment by cryos** [comment]
We will need to get the superbuild updated, I was hoping to look at some reported failure to optimize geometry on macOS - does this work for you @ghutchis with the superbuild?

**Comment by ghutchis** [comment]
It works with the "system" Open Babel installed from `master` - we should be tagging that release ASAP.

**Comment by ghutchis** [comment]
I'm still testing the molecules from Geoff Clark - seem to be different issues - that's not fixed yet.

**Comment by ghutchis** [comment]
The issue from Geoff Clark is #473 - the files are too big for Avogadro's MDL format code which silently causes problems.

**Comment by ghutchis** [comment]
@cryos - now that Open Babel 3.1 is merged, we should be able to merge this.

**Pull request merged**
