### PR TITLE
Modernized some code, willing to work on more. #1346

### PR DESCRIPTION
**Pull request by Kenshiro15**
#1346  **Description:**
#Used constexpr to define M_PI instead of a preprocessor macro.
#Removed #define preprocessor directive and used a more standard constexpr definition for M_PI.
#Updated loopvariables
I am also willing to change the variable types to use Eigen::Index, but i am a little unsure. I think it will ensure a better code.
I am new to opensource, and any newsuggestions would certainly be very helpful. 
Thank you!

### CODE REVIEW

**Comment by ghutchis** [comment]
Thanks. There is already a PR for constexpr M_PI #1383 but IIRC there are a few more like DEG_TO_RAD (see `avogadro/core/avogadrocore.h`)

This commit only includes `.vscode/settings.json` which frankly needs to go into the .gitignore file: https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files

**Comment by ghutchis** [comment]
I'm also not sure I understand what you mean by updating loop variables.

**Comment by Kenshiro15** [comment]
> Thanks. There is already a PR for constexpr M_PI #1383 but IIRC there are a few more like DEG_TO_RAD (see `avogadro/core/avogadrocore.h`)
> 
> This commit only includes `.vscode/settings.json` which frankly needs to go into the .gitignore file: https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files

I guess i made some mistakes in using github, sorry as i am a little bit new to it. I will get back to this asap.

**Comment by Kenshiro15** [comment]
> I'm also not sure I understand what you mean by updating loop variables.

We can use `size_t` instead of `unsigned int` (its not being used at someplaces), also we can use eigenMatrixx Eigen::Index,  in some of the loops.
Thank you for mentioning, i will get back to it.

**Comment by Kenshiro15** [comment]
> Thanks. There is already a PR for constexpr M_PI #1383 but IIRC there are a few more like DEG_TO_RAD (see `avogadro/core/avogadrocore.h`)
> 
Hello,  after taking your valuable  feedback, 
I have changed the following avagadrocore.h code as required with many necessary changes. May i submit a new PR, if you may allow?

**Comment by ghutchis** [comment]
Of course you can submit a new PR, thanks.

**Pull request closed without merging**
