### PR TITLE
WIP: LAMMPS Input generator

### PR DESCRIPTION
**Pull request by badarsh2**
image

Most of the raw content for this has been ported from Avogadro 1. A new modification I've brought here is the direct previewing of the molecule data file; in Avogadro 1, only the main file could be created using the input generator class and the data file had to be saved manually using the export option. Here I've made it such that the FileFormat class can be used to write out the molecule in a supported format and the output can be previewed alongside the main config file. In addition to that, I've made some other minor changes, for instance, the water potential option has been removed for now, as it requires some molecule-side information from the parent generator class. 

For now, the LAMMPS lmpdat data file is generated using OpenBabel writers; native lmpdat writer is still WIP. 

To check whether the generator does the job correctly, I tried generating inputs for bulk Silicon high temperature simulation. I had to manually add an extra line in the config file to read the Stillinger-Weber potentials for Silicon. Upon doing that and running the simulation using locally installed LAMMPS, it got completed without errors.

------------------------------------------------------------------------------------------------------------------
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by cryos** [comment]
This patch will need some work, we have moved the input generator Python code to a separate repository so that it can be updated between releases. I will update our documentation too, but it is important to only run clang-format on source that was changed, and source that is C++, i.e. CMakeLists.txt won't work. We need to use the git integration to only run it on the diff too, and I might need to update the .clang-format a little as it is really tough seeing what you actually changed versus unrelated changes made.

**Comment by ghutchis** [comment]
IMHO, for a complex input generator like this, the best approach will be to implement straight-up in Qt like APBS or GAMESS. It'll be easier to lay out the UI in Qt Designer, rather than hacking the input generator code for a lot of special cases.

**Comment by cryos** [comment]
I was wondering if that might be better too, and it wouldn't hurt to have a few more examples of specialized C++ input generators. You get events, more freedom, and we could always look at generalizing MD input in the future, but the current input generator code never considered MD.

**Comment by cryos** [comment]
No worries, it motivated me to improve our documentation a little, and point out a better way to do clang-format. I think a C++ generator would likely be the best solution at this stage.

**Pull request closed without merging**
