### PR TITLE
WIP: AppVeyor: build tests and run ctest after build

### PR DESCRIPTION
**Pull request by psavery**
Signed-off-by: Patrick Avery <psavery@buffalo.edu>

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by psavery** [comment]
It looks like it has some issues building gtest. 

Unfortunately, I'm shipping out my windows laptop today for a repair...

**Comment by ghutchis** [comment]
BTW, is there any way we can build a Windows package/installer from the AppVeyor build and save it (e.g., upload to GitHub)?

There's a PR for `cryos/avogadro` (https://github.com/cryos/avogadro/pull/907) that offers an AppVeyor build using a script like this:
https://github.com/probonopd/uploadtool

I'd be interested to work with you on a similar strategy for successful AppVeyor builds, since it would provide regular Windows binaries.

**Comment by psavery** [comment]
Yeah sure! I actually have something like this set up in my research group's program, XtalOpt: https://github.com/xtalopt/XtalOpt/blob/master/.appveyor.yml

Notice the 'artifacts' and 'deploy' sections at the end. I have it set up so that it will package and upload a release to GitHub when a new tag is pushed.

It might be easier to use that upload tool, though. Not sure.

**Comment by ghutchis** [comment]
Awesome! What's interesting about that PR is the "continuous" tag:
https://github.com/probonopd/avogadro/releases

**Comment by ghutchis** [comment]
@psavery - can we clean this up and merge?

**Comment by ghutchis** [comment]
I'm going to close this - I think we should drop the AppVeyor build - hopefully we can get the GitHub action working with Windows tests too.

**Pull request closed without merging**
