### PR TITLE
Newui rendersurfaces is done.

### PR DESCRIPTION
**Pull request by barrymoo**
@cryos @ghutchis NewQuantumOutput is done, sorry this took so long. All of this is working and ready to extend. If you guys like the new design I will merge it back to QuantumOutput.

### CODE REVIEW

**Comment by cryos** [comment]
Lumping everything together seems worse to me, so having the electronic surface lumped in with all the MOs makes it tougher to just calculate that when you want it. I also feel like you added a tabbed interface which takes up more space, offers redundant information, with the intent to add more tabs in the future?

What other tabs are you thinking of adding? I would like to overhaul this dialog, just not sure if this is really the right direction. I have started looking at the UI now that 0.8.0 has been tagged, and how it can be improved for end users. I would like to take the best from 1.x, and design some improved dialogs where cubes/other data should be easier to get at too.

**Comment by barrymoo** [comment]
@cryos ultimately the goal was to introduce my CubeFile code into this interface. A new tab would be made to manipulate surfaces calculated in Avogadro. For example, one can compute approximate transition densities, take derivatives, etc. I wanted to get the base interface done before I advanced.

I looked at Avogadro 1.x interface and streamlined it (minor). "Surface Type" can be chosen based on the input file (opening gaussian.chk can compute MOs or Density, opening *.cube is a Cube).

I can gladly add more things, modify things, etc. I just don't know what's best for the community.

**Comment by cryos** [comment]
That makes sense, I don't think lumping the electronic surface in with the molecular orbitals is the right thing to do. Same with cubes, I think there are so many MOs, and we necessarily want to put people in the middle with the HOMO/LUMO, then keeping them separate seems reasonable. We could just show the second level for MOs if MOs are available and selected. I will try to take a look at this again now your intent is a little clearer to me. Thanks for clarifying @barrymoo

**Comment by barrymoo** [comment]
@cryos Absolutely, I was hoping to use the same interface but customize based on the input file. Let me know what you decide, I will write the code.

**Comment by cryos** [comment]
Too much travel, I like your plans, and think we should continue down this path. We should replace the existing menu as it would be confusing to keep both.

**Comment by barrymoo** [comment]
@cryos, hopefully for enjoyable reasons. I will replace the "old" interface as soon as I can.

**Comment by ghutchis** [comment]
@barrymoo Are you still thinking of merging this branch? I think allowing import of surface/cube data is great, particularly since there are other formats (e.g., APBS generates OpenDX or some such.)

**Comment by barrymoo** [comment]
@ghutchis Yes, I am having some trouble with my current forks. I will figure this out in the afternoon.

**Comment by barrymoo** [comment]
Resurrected https://github.com/OpenChemistry/avogadrolibs/pull/62/commits/e9178090b83ff64abf961b85dd6f736eec81f509

**Comment by ghutchis** [comment]
Can we close this in favor of #62 ?

**Comment by barrymoo** [comment]
Yes.

**Pull request closed without merging**
