### PR TITLE
Edit molecule name, charge, and spin in properties

### LINKED ISSUE #1059: Total Charge / Spin Multiplicity
File import / export and input generators need better support for total charge / spin multiplicity.

If I read in a calculation, the program should know *throughout* that the total charge / spin is set (e.g., H3O+ or OH-, etc.)

PR #1058 gets things started
- [x] `quantumio` readers need update
- [x] input generator scripts should get total charge and spin through JSON

### PR DESCRIPTION
**Pull request by ghutchis**
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ghutchis** [comment]
Thoughts @matterhorn103

**Comment by matterhorn103** [comment]
Looks good to me! :)

The first thing I notice is that the spin can go lower than 1, which obviously it shouldn't.

Secondly, we know for a fact that some combinations of charge and spin are not valid based on the proton count, so is it possible that we can have the +/- arrows be a bit smarter? By that I mean:

1. Every time the charge is changed by 1 using the arrows the spin should change by 1 to match, either from 1 to 2 or 2 to 1 (i.e. the spin is always the lowest valid value)
2. When the spin is changed with the arrows it should go in steps of 2 (and the charge is not changed). That way the arrows cycle between the valid spin states. For example incrementing the spin of a singlet would make it a triplet. This halves the number of necessary clicks!
3. None of this should apply to when the numbers are typed, where the user should be able to choose freely just as they can now - this is important so they can override any errors in Avogadro's logic

If you were *particularly* keen for suggestions I'd also say that in an ideal world you would see the +/- arrows even before you click the field so it's clear they're editable, like how it is in the Manipulate Tool for example. But I suspect your choice of widgets is limited in the table?

**Comment by ghutchis** [comment]
> The first thing I notice is that the spin can go lower than 1, which obviously it shouldn't.

Ugh, that was a typo. Sorry.

> When the spin is changed with the arrows it should go in steps of 2 (and the charge is not changed). That way the arrows cycle between the valid spin states. For example incrementing the spin of a singlet would make it a triplet. This halves the number of necessary clicks!

I think you mean in the input generators? At least for me, the table doesn't show any kind of arrows. There is only minimal validation at the moment.

I get your idea (i.e., to make sure the number is always valid) but I think I'd still leave it to the user. What if I have a molecule and want to run the radical cation. Do I have to change the charge before I can change the spin state? That seems non-intuitive. Some sort of color or warning that the spin state and charge are inconsistent might make sense though.

There's some code in the `Molecule` class that works like you describe. If I draw out a molecule and change the charge to +1 or -1, it will change the auto-defined multiplicity to 2 (and back to 1) according to the number of electrons.

**Comment by matterhorn103** [comment]
> I think you mean in the input generators? At least for me, the table doesn't show any kind of arrows.

No, I mean in the molecular properties table. They only show up when I click to edit the fields, but they're there.

> What if I have a molecule and want to run the radical cation. Do I have to change the charge before I can change the spin state?

The way I'm suggesting, you would in this case never have to change the spin state, because it would automatically be the radical cation after increasing the charge.

Maybe the idea would be more intuitive if it was separate buttons  labelled as what they actually are: "add/remove an electron" and "increase/decrease spin".

> There's some code in the `Molecule` class that works like you describe. If I draw out a molecule and change the charge to +1 or -1, it will change the auto-defined multiplicity to 2 (and back to 1) according to the number of electrons.

Good to know :)

> But some of this is probably better on the forum than buried in the pull request comments.

Probably, I can open a thread tomorrow if you don't.

**Pull request merged**
