### PR TITLE
Migrate to a unified Python script loading code.

### PR DESCRIPTION
**Pull request by ghutchis**
Eliminates duplicate code between different script types
but also gives one place to handle conflict resolution, etc.

### CODE REVIEW

**Comment by ghutchis** [comment]
There's a bit of work to fully migrate the formats plugin to use this new class, but I'm punting on that for now. This will make it much easier to add new script types (e.g., `charges` and `forcefields` next).

- Downloaded plugins can now replace "released" plugins
- Subdirectory packages with plugin.json (e.g., separate "real" commands from tests, library code)
- One place for changing script loading behavior

**Comment by ghutchis** [comment]
This also fixes #235

**Comment by ghutchis** [comment]
Supposedly the AppVeyor failure is in Eigen?!

I'm going to see what I can do to bump and re-build.

**Comment by cryos** [comment]
That is odd, I am trying to get some patches finished up, but can test it out on Linux. I haven't seen Eigen failures, and see nothing in the changes that would cause an Eigen failure. Sometimes the build machines glitch.

**Comment by cryos** [comment]
I see a lot of:
`ScriptLoader::queryProgramName: Unable to retrieve program name for "/home/marcus/build/openchemistry/prefix/lib64/avogadro2/scripts/inputGenerators/terachem.py" ; "Error running script '/usr/bin/python2 /home/marcus/build/openchemistry/prefix/lib64/avogadro2/scripts/inputGenerators/terachem.py --display-name --lang en_US': Abnormal exit status 2 (Unknown error.: Unknown error)\n\nOutput:\nusage: Generate a TeraChem input file. [-h] [--debug] [--print-options]\n                                       [--generate-input] [--display-name]\nGenerate a TeraChem input file.: error: unrecognized arguments: --lang en_US\n"`
Copying the avogenerator scripts fixes this, so I assume it implicitly needs the avogenerator branches to be merged to remain functional.

**Comment by cryos** [comment]
Looks good otherwise, seems to work for input generators once the other branch is in place. Would like to either remove the --lang, or hold this until we can merge avogenerator integration.

**Comment by cryos** [comment]
I think this is ready to go now that the generators can accept the --lang argument

**Pull request merged**
