### PR TITLE
Compiler warnings

### PR DESCRIPTION
**Pull request by cryos**

### CODE REVIEW

**Comment by ghutchis** [comment]
Some minor warnings by Codacy (e.g., initializing member variables)
Screenshot 2023-04-15 at 5 01 02 PM

**Comment by cryos** [comment]
Fixed those two, strange I did not see the same report.

**Comment by ghutchis** [comment]
At some point last summer to help catch some of these issues, I added a bunch of static analysis tools. (Getting `clang-tidy` to fully work is still not finished.)

At a minimum, you can look at the builds:
Screenshot 2023-04-15 at 5 37 55 PM

**Comment by cryos** [comment]
I am going to circle back to a few of the initialization issues pointed out in a follow up commit. They have been there for a long time, just this branch touches quite a bit of code. I have noted them down, but want to merge this and then make a few more focused follow up PRs. I think this is a good point to merge.

**Pull request merged**
