### PR TITLE
Symmetry Properties via libmsym 

### PR DESCRIPTION
**Pull request by ghutchis**
Updated @mcodev31 libmsym plugin, including symmetry rendering and subgroups.

Requires openchemistry pull:
https://github.com/OpenChemistry/openchemistry/pull/20

This does *not* require VLA, so I'm hopeful for compiler compatibility.

Does not (yet) implement symmetry-equivalent atoms

screen shot 2016-12-30 at 11 54 12 am

### CODE REVIEW

**Comment by ghutchis** [comment]
While I'd categorize this as "in progress" due to the missing "equivalent atoms" list, it seems fairly solid.

I will add a "flatten molecule" workflow script, since some molecules are far from planar and libmsym can't do much.

**Comment by cryos** [comment]
This fails to compile for me on Windows, Arch Linux and Ubuntu Linux. The failures all look pretty similar, the full output on Ubuntu is:

$ ninja -j1
[26/242] Building CXX object avogadro/...CMakeFiles/Symmetry.dir/symmetry.cpp.o
FAILED: /usr/bin/c++   -DQT_CORE_LIB -DQT_GUI_LIB -DQT_STATICPLUGIN -DQT_WIDGETS_LIB -I. -I/home/marcus/src/openchemistry/avogadrolibs -Iavogadro/core -Iavogadro/io -Iavogadro/quantumio -Iavogadro/rendering -Iavogadro/qtgui -Iavogadro/qtopengl -Iavogadro/molequeue -isystem /usr/include/eigen3 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/marcus/build/openchemistry/prefix/lib/cmake/libmsym/../../../include -Iavogadro/qtplugins/symmetry -g -Wnon-virtual-dtor -Wno-long-long -Wcast-align -Wchar-subscripts -Wall -Wpointer-arith -Wformat-security -Woverloaded-virtual -fno-check-new -fno-common -pedantic -Wshadow -Wextra -Werror=return-type -fvisibility=hidden -fvisibility-inlines-hidden   -fPIC -fPIC -std=c++11 -MMD -MT avogadro/qtplugins/symmetry/CMakeFiles/Symmetry.dir/symmetry.cpp.o -MF avogadro/qtplugins/symmetry/CMakeFiles/Symmetry.dir/symmetry.cpp.o.d -o avogadro/qtplugins/symmetry/CMakeFiles/Symmetry.dir/symmetry.cpp.o -c /home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetry.cpp
/home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetry.cpp: In member function ‘void Avogadro::QtPlugins::Symmetry::detectSymmetry()’:
/home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetry.cpp:253:75: error: invalid conversion from ‘msym::msym_symmetry_operation_t** {aka msym::_msym_symmetry_operation**}’ to ‘const msym_symmetry_operation_t** {aka const msym::_msym_symmetry_operation**}’ [-fpermissive]
   if(MSYM_SUCCESS != (ret = msymGetSymmetryOperations(ctx, &msopsl, &msops))) {
                                                                           ^
In file included from /home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/operationstablemodel.h:22:0,
                 from /home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetrywidget.h:33,
                 from /home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetry.h:22,
                 from /home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetry.cpp:17:
/home/marcus/build/openchemistry/prefix/lib/cmake/libmsym/../../../include/libmsym/msym.h:182:30: note:   initializing argument 3 of ‘msym::msym_error_t msym::msymGetSymmetryOperations(msym::msym_context, int*, const msym_symmetry_operation_t**)’
     msym_error_t MSYM_EXPORT msymGetSymmetryOperations(msym_context ctx, int *sopsl, const msym_symmetry_operation_t **sops);
                              ^
/home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetry.cpp:281:64: error: invalid conversion from ‘msym::msym_subgroup_t** {aka msym::_msym_subgroup**}’ to ‘const msym_subgroup_t** {aka const msym::_msym_subgroup**}’ [-fpermissive]
     if(MSYM_SUCCESS != (ret = msymGetSubgroups(ctx, &msgl, &msg))) {
                                                                ^
In file included from /home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/operationstablemodel.h:22:0,
                 from /home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetrywidget.h:33,
                 from /home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetry.h:22,
                 from /home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetry.cpp:17:
/home/marcus/build/openchemistry/prefix/lib/cmake/libmsym/../../../include/libmsym/msym.h:180:30: note:   initializing argument 3 of ‘msym::msym_error_t msym::msymGetSubgroups(msym::msym_context, int*, const msym_subgroup_t**)’
     msym_error_t MSYM_EXPORT msymGetSubgroups(msym_context ctx, int *l, const msym_subgroup_t **subgroups);
                              ^
/home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetry.cpp:190:15: warning: unused variable ‘error’ [-Wunused-variable]
   const char *error = NULL;
               ^
/home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetry.cpp:192:31: warning: unused variable ‘symerr’ [-Wunused-variable]
   double cm[3], radius = 0.0, symerr = 0.0;
                               ^
/home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetry.cpp:197:29: warning: unused variable ‘mlength’ [-Wunused-variable]
   int msgl = 0, msopsl = 0, mlength = 0;
                             ^
/home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetry.cpp: In member function ‘void Avogadro::QtPlugins::Symmetry::symmetrizeMolecule()’:
/home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetry.cpp:331:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if(mlength != length)

**Comment by ghutchis** [comment]
@cryos - the commit is unrelated (but useful) and I think with the updated openchemistry pull, it should work.

**Comment by cryos** [comment]
Trying it locally, and it looks better, I get failures of the following form now,

/home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetrywidget.cpp:36:40: warning: ISO C++ does not allow C99 designated initializers [-Wpedantic]
   msym_thresholds_t tight_thresholds = { // all defaults
                                        ^
/home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetrywidget.cpp:37:21: warning: ISO C++ does not allow C99 designated initializers [-Wpedantic]
       .zero = 1.0e-3,
                     ^
/home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetrywidget.cpp:38:25: warning: ISO C++ does not allow C99 designated initializers [-Wpedantic]
       .geometry = 1.0e-3,
                         ^
I am just looking into if I can remove that flag just for libmsym, although I wonder if this will compile on VS2015 as it has no C99 support to speak of.

**Comment by cryos** [comment]
It seems the issue is in mixing this with C++ in g++ at least, some results led me to take a look at https://github.com/doslab/gcc-designated-initializer-support-cpp/wiki/GCC-Support-for-Non-trivial-designated-initializer-in-CPP

**Comment by cryos** [comment]
I think worst case is going to be rewriting the initializer code that makes use of C99, it does look like convenient API, but the repetition shouldn't be too bad.

**Comment by mcodev31** [comment]
Hi

Sorry I’m a bit quiet. Lots to do. I’ll look at this more as soon as I can (not before the 4th jan though). Looks great!
As far as I can tell these errors are in the c++ side (symmetrywidget.cpp), so this should be fixable within Avogadro.
If you find you have to rewrite/duplicate code in libmsym or jump through hoops to get things working, then please just report a bug/issue on github and I’ll fix it.
This is supposed to be a functioning, usable library after all.

/M

**Comment by cryos** [comment]
Thanks, and I agree from a quick look it appears to be calling code in the C++ that is having issues, not the library headers etc. It is a shame that these C99 features weren't better integrated with C++11 but reading around it seems like there are some compatibility issues.

**Comment by ghutchis** [comment]
@mcodev31 - no problem, it took us a while to get back to the pull request.

Out of curiosity, what did you have in mind for the table under the "Molecule" tab? Obviously, lists of the symmetry-unique atoms (e.g., from `msymGetEquivalenceSets(ctx, &mesl, &mes)`)

Was the idea that you'd click a symmetry-unique atom and all the equivalent ones would be selected in the molecule?

If you can give me an idea what should go in that table, I should have time this week to do it.

**Comment by cryos** [comment]
This will not compile for me, I merged the other branch in openchemistry, it seems to me that the C99 style calls will have to be rewritten, but the headers are fine in the library.

**Comment by mcodev31** [comment]
@cryos Is this windows? Could you paste some compiler output? In case of windows: are you using the cmake flag for disabling VLA from the dev branch?

**Comment by cryos** [comment]
@mcodev31 no this is Linux, due to the C++11 compiler not having the necessary C99 features, using GCC 6.3.1, but we would like to support older GCC versions than that too. Some of the output seen:

/usr/bin/c++   -DQT_CORE_LIB -DQT_GUI_LIB -DQT_STATICPLUGIN -DQT_WIDGETS_LIB -I. -I/home/marcus/src/openchemistry/avogadrolibs -Iavogadro/core -Iavogadro/io -Iavogadro/quantumio -Iavogadro/rendering -Iavogadro/qtgui -Iavogadro/qtopengl -Iavogadro/molequeue -isystem /usr/include/eigen3 -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -isystem /usr/lib/qt/mkspecs/linux-g++ -I/home/marcus/build/openchemistry/prefix/lib/cmake/libmsym/../../../include -Iavogadro/qtplugins/symmetry -g -Wnon-virtual-dtor -Wno-long-long -Wcast-align -Wchar-subscripts -Wall -Wpointer-arith -Wformat-security -Woverloaded-virtual -fno-check-new -fno-common -pedantic -Wshadow -Wextra -Werror=return-type -fvisibility=hidden -fvisibility-inlines-hidden   -fPIC -fPIC -std=c++11 -MD -MT avogadro/qtplugins/symmetry/CMakeFiles/Symmetry.dir/symmetrywidget.cpp.o -MF avogadro/qtplugins/symmetry/CMakeFiles/Symmetry.dir/symmetrywidget.cpp.o.d -o avogadro/qtplugins/symmetry/CMakeFiles/Symmetry.dir/symmetrywidget.cpp.o -c /home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetrywidget.cpp
/home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetrywidget.cpp:36:40: warning: ISO C++ does not allow C99 designated initializers [-Wpedantic]
   msym_thresholds_t tight_thresholds = { // all defaults
                                        ^
/home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetrywidget.cpp:37:21: warning: ISO C++ does not allow C99 designated initializers [-Wpedantic]
       .zero = 1.0e-3,
                     ^
/home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetrywidget.cpp:38:25: warning: ISO C++ does not allow C99 designated initializers [-Wpedantic]
       .geometry = 1.0e-3,
                         ^
/home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetrywidget.cpp:39:22: warning: ISO C++ does not allow C99 designated initializers [-Wpedantic]
       .angle = 1.0e-3,
                      ^
/home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetrywidget.cpp:40:28: warning: ISO C++ does not allow C99 designated initializers [-Wpedantic]
       .equivalence = 5.0e-4,
                            ^
/home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetrywidget.cpp:41:28: warning: ISO C++ does not allow C99 designated initializers [-Wpedantic]
       .permutation = 5.0e-3,
                            ^
/home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetrywidget.cpp:42:24: warning: ISO C++ does not allow C99 designated initializers [-Wpedantic]
       .eigfact = 1.0e-3,
                        ^
/home/marcus/src/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetrywidget.cpp:44:3: sorry, unimplemented: non-trivial designated initializers not supported
   };
   ^

**Comment by mcodev31** [comment]
@cryos Oh, right sorry, we already talked about this, the problem was in symmetrywidget.cpp.
C99 and C++11 arn't supposed to be compatible so that problem is understandable (though the decision not to make them compatible is not).
In this particular case it's just a matter of removing the struct member names (with correct ordering) or initialising the values in the constructor. Constructor is probably more future proof.

**Comment by cryos** [comment]
That is the one, and I agree with you on the decision... As you say, this is now on the Avogadro code side, I can take a look and see how tough this looks when I have a moment if @ghutchis doesn't get a chance.

**Comment by cryos** [comment]
So I rebased, migrated, made it compile with GCC, and applied the automatic code styling. In basic tests this works for me, and should not merge cleanly.

**Comment by ghutchis** [comment]
should "not" merge cleanly?

Am I okay to merge?

**Pull request merged**
