### PR TITLE
Clang format

### PR DESCRIPTION
**Pull request by cryos**

### CODE REVIEW

**Comment by ghutchis** [comment]
I'm fine with the patch, but this was marked as "in progress" - is it ready to merge?

**Comment by cryos** [comment]
I meant to circle back to this, and see if there were objections, I can merge what we have here, and then work on getting as many branches merged as possible before applying the style to all source files in a follow up branch. We have been exploring using CI with GitHub, and can hopefully translate over some of the stuff we are doing in Tomviz to this soon too, including running clang-format and flake8 for more consistent style.

**Comment by ghutchis** [comment]
FYI, I asked Ethan to prepare an AppVeyor build for avogadrolibs. I'll find out tomorrow how that's progressing.

**Comment by cryos** [comment]
Sounds good, we can use the results of the recent Tomviz work to use AppVeyor for Windows, CircleCI for Linux, and Travis for clang-format builds. They should all be pretty easy to replicate, and we will have some funding/time to add these things in early March/April.

**Pull request merged**
